<a href="https://colab.research.google.com/github/ms-daniel/ArvoreGrafoJogoDaVelha/blob/master/IEx09_Rede_Neural_PACIENTES%20-%20One%20Rule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [11]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/ms-daniel/Exercicio-IA-Rede-Neural/main/dados_pacientes_treinamento.csv'
base_Treinamento = pd.read_csv(url,sep=';', encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 1:5])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 5])

---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
[['João' 'sim' 'sim' 'pequenas' 'sim' 'doente']
 ['Pedro' 'não' 'não' 'grandes' 'não' 'saudável']
 ['Maria' 'sim' 'sim' 'pequenas' 'não' 'saudável']
 ['José' 'sim' 'não' 'grandes' 'sim' 'doente']
 ['Ana' 'sim' 'não' 'pequenas' 'sim' 'saudável']
 ['Leila' 'não' 'não' 'grandes' 'sim' 'doente']]
---------------------------------
Atributos de Entrada
---------------------------------
[['sim' 'sim' 'pequenas' 'sim']
 ['não' 'não' 'grandes' 'não']
 ['sim' 'sim' 'pequenas' 'não']
 ['sim' 'não' 'grandes' 'sim']
 ['sim' 'não' 'pequenas' 'sim']
 ['não' 'não' 'grandes' 'sim']]
----------------------------
Classificação Supervisionada
----------------------------
['doente' 'saudável' 'saudável' 'doente' 'saudável' 'doente']


### Pré-processamento de Dados

In [12]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.LabelBinarizer()

#A saída da transformação é também conhecido como codificação 1-de-n
#Transforma valores categóricos equidistantes em valores binários equidistantes.
#Atributos categóricos com valores sim e não
lb.fit(['sim', 'não'])
febre = lb.transform(base_Treinamento[:,1])  
enjoo = lb.transform(base_Treinamento[:,2])
dores = lb.transform(base_Treinamento[:,4])

#Atributos categóricos com valores pequenas e grandes
lb.fit(['grandes', 'pequenas'])
manchas = lb.transform(base_Treinamento[:,3])

#Atributos categóricos com valores saudável e doente
lb.fit(['saudável', 'doente'])
classes = lb.transform(base_Treinamento[:,5])

#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((febre,enjoo,manchas,dores))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
diagnostico_norm = np.hstack((classes))
print(diagnostico_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[1 1 1 1]
 [0 0 0 0]
 [1 1 1 0]
 [1 0 0 1]
 [1 0 1 1]
 [0 0 0 1]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[0 1 1 0 1 0]


### Treinamento do Neurônio Perceptron

In [13]:
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC

#from sklearn.linear_model import Perceptron
# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = OneVsOneClassifier(LinearSVC(random_state=0))
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo. 
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

Acurácia: 1.000


### ----------------------------------------------------------------------------

# Validação do Aprendizado 

### Predição Simples

In [14]:
Luiz = [[0,0,1,1]]
print("Luiz", modelo.predict(Luiz))
Laura = [[1,1,0,1]]
print("Laura", modelo.predict(Laura))

Luiz [1]
Laura [0]


### Predição a partir de base de dados de teste (.csv)

In [15]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/ms-daniel/Exercicio-IA-Rede-Neural/main/dados_pacientes_treinamento.csv'
base_Testes = pd.read_csv(url,sep=';', encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 1:5])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[['João' 'sim' 'sim' 'pequenas' 'sim' 'doente']
 ['Pedro' 'não' 'não' 'grandes' 'não' 'saudável']
 ['Maria' 'sim' 'sim' 'pequenas' 'não' 'saudável']
 ['José' 'sim' 'não' 'grandes' 'sim' 'doente']
 ['Ana' 'sim' 'não' 'pequenas' 'sim' 'saudável']
 ['Leila' 'não' 'não' 'grandes' 'sim' 'doente']]
---------------------------------
Atributos de Entrada
---------------------------------
[['sim' 'sim' 'pequenas' 'sim']
 ['não' 'não' 'grandes' 'não']
 ['sim' 'sim' 'pequenas' 'não']
 ['sim' 'não' 'grandes' 'sim']
 ['sim' 'não' 'pequenas' 'sim']
 ['não' 'não' 'grandes' 'sim']]


### Pré-processamento de Dados

In [16]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.LabelBinarizer()

#A saída da transformação é também conhecido como codificação 1-de-n
#Transforma valores categóricos equidistantes em valores binários equidistantes.
#Atributos categóricos com valores sim e não
lb.fit(['sim', 'não'])
febre = lb.transform(base_Testes[:,1])  
enjoo = lb.transform(base_Testes[:,2])
dores = lb.transform(base_Testes[:,4])

#Atributos categóricos com valores pequenas e grandes
lb.fit(['grandes', 'pequenas'])
manchas = lb.transform(base_Testes[:,3])

#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((febre,enjoo,manchas,dores))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)


--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[1 1 1 1]
 [0 0 0 0]
 [1 1 1 0]
 [1 0 0 1]
 [1 0 1 1]
 [0 0 0 1]]


### Predição da Base

In [17]:
base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

Classificações:  [0 1 1 0 1 0]
